### ISSUE TITLE
listen tcp: address 8080: missing port in address

### ISSUE THREAD

**Issue by marcusteixeira** [martin-duerre/unity2promgo#1]
Running Unity Export with default configs:

`./unity2promgo`

My Configs(example used of port field): 

{
  "exporter": {
    "port": "8080",
    "interval": 60,
    "pools": false,
    "storage_resources": false,
    "metrics":}}

it gives the following logs:

2020/01/14 18:05:15 main.go:main - Create unity Session: ip
2020/01/14 18:05:17 main.go:main - Unity Name: unityname
2020/01/14 18:05:17 unityCollector.go:NewUnityCollector - Unity: unityname
2020/01/14 18:05:17 1
2020/01/14 18:05:17 listen tcp: address 8080: missing port in address

**Comment by marcusteixeira** [comment]
@martin-duerre

**Comment by kdessai19** [comment]
@martin-duerre / @marcusteixeira  was this pull request ever approved? 

If i set  `"storage_resources": true`, in configs.json i get hit with the below error

```
panic: runtime error: index out of range [0] with length 0

goroutine 26 [running]:
main.UnityCollector.CollectStorageResourceMetrics.func1()
        /splunk/goprojects/unity2promgo/unitycollector.go:222 +0x509
created by main.UnityCollector.CollectStorageResourceMetrics
        /splunk/goprojects/unity2promgo/unitycollector.go:210 +0xaa
```

If `"storage_resources": false` i see below but doesn't seems to be fetching any metrics,

```
2022/04/17 08:06:08 main.go:main - Create unity Session: ##.##.##.##
2022/04/17 08:06:09 main.go:main - Unity Name: MYUNITYSERVER
2022/04/17 08:06:09 unityCollector.go:NewUnityCollector - Unity: MYUNITYSERVER
2022/04/17 08:06:09 1
2022/04/17 08:06:31 UnityCollector - Collector: Query Realtime Metrics with interval
```
